### ISSUE TITLE
Cannot type spaces

### ISSUE THREAD

**Issue by Frando** [cabal-club/cabal#104]
With cabal 5.2.0 I cannot type any spaces.

Tested with Termite + tmux, Termite without tmux, Gnome Terminal. Node 11, arch linux.

**Comment by cblgh** [comment]
Yeah hmmm this was an issue before 5.2.0, now I just have to figure out how to replicate it

*scratches head*

**Comment by ralphtheninja** [comment]
@cblgh Are you running mac and can't reproduce?

**Comment by cblgh** [comment]
@ralphtheninja yeah, and a debian server running a cli session in tmux

albeit i've been running straight from the repo code and not a globally installed `npm i -g cabal`, so there could be a discrepancy there somehow

**Comment by cblgh** [comment]
found the problem! i made a pr above ^

**Comment by telamon** [comment]
`package-lock` is pretty damn broken/unstable, i had an argument with the devs about that issue.
I think i ended up with the recommendation to manually shrinkwrap before each release:
`npm shrinkwrap` generates a publishable lock-file.
