### ISSUE TITLE
maxFeeds isn't being passed down to hypercore-protocol

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal#106]
`maxFeeds` is set to 1000 by default, but when I `console.log` `opts.maxFeeds` in hypercore-protocol it's being set to 256 instead. Somewhere down the stack the value is being lost.

**Comment by karissa** [comment]
I think this might be getting lost in multifeed's replicate
https://github.com/kappa-db/multifeed/blob/master/index.js#L274 is using `opts` from the replicate, whereas `maxFeeds` is being sent in the constructor instead (seems unused)
