### ISSUE TITLE
fix issue with wrapping lines affecting the terminal display

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal#14]
i think one of the current rendering issues has to do with when a line exceeds the terminal width, causing it to wrap to a new row

on rendering we should calculate how many of the visible messages will do this and change the amount of lines we display as a result

e.g. ![an example](https://i.cblgh.org/2018-05/24686mf.png)

**Comment by cblgh** [comment]
started a branch where i'm trying to work on this https://github.com/cabal-club/cabal/tree/improve-neat-rendering

**Comment by joehand** [comment]
Looks like you may have solved it, but https://github.com/sindresorhus/string-width was helpful for me previously when dealing with wrapping strings.
