### ISSUE TITLE
implement page up/down to scroll through the backlog

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal#15]
this could be implemented similar to #4 (wrt `neat-input` at least!)

**Comment by joehand** [comment]
It'd be cool for this to be a generic neat-log module (input array of messages and get out fullscreen view plus up/down input handling)!

**Comment by ralphtheninja** [comment]
Could use `cabal` to implement it as a stand alone file and then extract it to a module.

**Comment by voidcase** [comment]
Done: https://github.com/cabal-club/cabal/pull/25/
