### ISSUE TITLE
use npm published version of cabal-node and hyperdb

### ISSUE THREAD

**Issue by karissa** [cabal-club/cabal#16]
hyperdb and cabal-node are being referenced in package.json at their github versions, which will cause incompatibility with different installations of cabal depending on when the person installed cabal. It also means incompatibility with other clients (such as Desktop, which depends on particular npm versions).

Can we use npm published versions of these repositories? This also means that we will likely need to advance cabal-node through npm rapidly, but it is better software release practice overall and will improve reliability.

https://github.com/cabal-club/cabal/blob/master/package.json#L15

**Comment by cblgh** [comment]
Yeah! I'm all for this! I was just being a hacky hackson when I did that initially, I'll follow your lead re versioning of cabal-node as I'm not that experienced with minting semver releases

**Comment by karissa** [comment]
A good rule of thumb:
 - backwards compatibility change use `npm version major`
 - new feature `npm version minor`
 - bug `npm version patch`

then do `git push --tags origin master`
and then `npm publish`

**Comment by cblgh** [comment]
alright! i just published [`cabal@2.0.0`](https://www.npmjs.com/package/cabal) and [`cabal-node@2.0.0`](https://www.npmjs.com/package/cabal-node)

**Comment by karissa** [comment]
nice!!!
