### ISSUE TITLE
add /me command for text emotes

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal#22]
this should be implemented in commands.js using a message posted via `cabal-node` with the `opts.type` set to `chat/emote`

**Comment by cblgh** [comment]
added in https://github.com/cabal-club/cabal/commit/0c2427a09d150aa914afd8461ac1320c1f8b1089

**Comment by karissa** [comment]
It'd be cool if '/me' was kept in the database message content, and the type stayed `chat/emote` and the rendering is then handled by the client instead of baked into the database.
