### ISSUE TITLE
Duplicate channels

### ISSUE THREAD

**Issue by ralphtheninja** [cabal-club/cabal#24]
![screenshot from 2018-05-28 23-50-47](https://user-images.githubusercontent.com/308049/40630327-1fd53c6e-62d2-11e8-84a2-401e86aa8de1.png)

**Comment by ralphtheninja** [comment]
If I do `ctrl+n` and `ctrl+p` I never end up on the first line, so I think it's some rendering issue.

**Comment by ralphtheninja** [comment]
One more screenshot

![screenshot from 2018-05-29 01-55-45](https://user-images.githubusercontent.com/308049/40632082-7e70fdf6-62e3-11e8-8be8-1e4fb20f2e05.png)

I think this is related to the first line. When I flip between the channels I see @noffle 's message on all channels, and I also see my name twice.

**Comment by ralphtheninja** [comment]
Stopped being a problem for some reason.

**Comment by karissa** [comment]
@ralphtheninja i wonder if it still shows up for you after we merge https://github.com/cabal-club/cabal/pull/27, which now checks for duplicates

**Comment by ralphtheninja** [comment]
![screenshot from 2018-05-30 22-28-14](https://user-images.githubusercontent.com/308049/40745822-ce3f05aa-6458-11e8-8924-680885b6d5d1.png)

**Comment by ralphtheninja** [comment]
@karissa Cool. I'll check once it's merged.

**Comment by karissa** [comment]
@ralphtheninja ok i merged it, seems to work well for me

**Comment by ralphtheninja** [comment]
Still have the same rendering issues :cry:

**Comment by karissa** [comment]
AH sorry didn't realize this is triggered by +n and +p

**Comment by ralphtheninja** [comment]
It's not triggered by that either. It just happens a while after I start the application.

**Comment by noffle** [comment]
I've noticed a bug where I *think* we're drawing on the final terminal line, which induces a scroll and, I think, confuses diffy permanently.

**Comment by ralphtheninja** [comment]
No longer an issue.
