### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ralphtheninja** [cabal-club/cabal#26]
I propose GPL :)

**Comment by noffle** [comment]
cc all code contributors of this repo:

- [ ] @cblgh: `null`
- [ ] @noffle: `GPL || AGPL`
- [ ] @kodedninja: `null`
- [ ] @karissa: `null`
- [ ] @Powersource: `null`
- [ ] @ralphtheninja: `GPL`

**Comment by Powersource** [comment]
GPL sounds good :)

**Comment by kodedninja** [comment]
GPL is okay :)
