### ISSUE TITLE
Sometimes messages are shown twice

### ISSUE THREAD

**Issue by soyuka** [cabal-club/cabal#29]
![bug_cabal](https://user-images.githubusercontent.com/1321971/40724413-4d2423b0-6421-11e8-869a-89c5a086e47d.png)

Not sure if this comes from screen drawing or that the message is indeed received twice (cabal-node)

#24 
Looks like it's a rendering issue only.

**Comment by cblgh** [comment]
new database, new problems (closing this since we have [multifeed](https://github.com/noffle/multifeed) as the backing store now!)
