### ISSUE TITLE
Bug with backscroll on first join

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal#3]
it looks like people are having an issue with not seeing any backscroll when they first start cabal up and enter a populated channel

rejoining the channel using `/change <channel>` fixes it

there's probably some little tweak needed in [neat-screen](https://github.com/cabal-club/cabal/blob/master/neat-screen.js)

(maybe we need to attach a listener to `self.cabal.db.on('append', cb)` & `self.cabal.db.on('remote-update', cb)` ?)

**Comment by kodedninja** [comment]
little note, but not just on first join, but on every join if there are more than 1 new messages.
