### ISSUE TITLE
Fix Rendering Issues

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal#32]
Cabals with many messages have issues rendering them properly. Often times the input bar is overwritten, or collides with the backlog and the nick window seemingly has duplicates.

I think these issues stem from bugs in [diffy](https://github.com/mafintosh/diffy) and maybe also from [txt-blit](https://github.com/noffle/txt-blit) (since they are used in combination). 

I want to start august's coding off by either finding and defeating these bugs, or by writing a new cli-frontend that doesn't suffer from them.

### Rendering issues 
* [Rendering issues with emojis](https://github.com/cabal-club/cabal/issues/55)
* [Multi-line pastes not showing up reliably](https://github.com/cabal-club/cabal/issues/71)
* [Newline-containing messages are not wrapped properly](https://github.com/cabal-club/cabal/issues/67)

**Comment by julianpistorius** [comment]
I think I've started disentangling things. 

I also see issue #10, and I suspect this warning might be causing a rendering issues for me as soon as the app starts - but only on Node 10.3.0.

When I use Node 9.11.1 I don't see this warning, and I also don't see the rendering issue when the app starts. But I do see the same rendering issue later on if I type long sentences with many words.

Fundamentally what I think triggers the rendering issue is when the input in the text entry area at the bottom of the screen grows beyond a certain size. Issue #10 just happens to trigger the rendering issue earlier.

## Test environment

Operating System: Mac OS X 10.11.6 (El Capitan)
Cabal version: 2.3.1
Git hash: `49ab4b4276a4360e3dc5a98ac44e9df1f31f5ef8`
Bash: GNU bash, version 4.4.19(1)-release (x86_64-apple-darwin15.6.0)
Readline: stable 7.0.3 (bottled), devel 8.0-alpha [keg-only]

### Screencast

[![asciicast](https://asciinema.org/a/Z3gOoIkQA33tyguzHuzvN4M5Y.png)](https://asciinema.org/a/Z3gOoIkQA33tyguzHuzvN4M5Y?speed=2)

### Screenshots

<details>
    <summary>Screenshot: Node 10, with warning and rendering issue</summary>
    <p>
        <img width="1441" alt="node_10_warning_and_rendering_issue" src="https://user-images.githubusercontent.com/742633/40810653-f9305898-651d-11e8-9ba9-6d3b727754bf.png">
    </p>
</details>
<details>
    <summary>Screenshot: Node 9, no warning, but still rendering issue</summary>
    <p>
        <img width="1438" alt="node_9_no_warning_but_still_rendering_issue" src="https://user-images.githubusercontent.com/742633/40810692-27c6601c-651e-11e8-916b-f2835fd61f5f.png">
    </p>
</details>

**Comment by cblgh** [comment]
@julianpistorius wow i can't believe i missed this excellent screencast, thank you so much! 

i think you might be right in the problems stemming from text areas becoming outsized. it looks like this causes issues in [diffy](https://github.com/mafintosh/diffy/)

[scat](https://github.com/stripedpajamas/scat) has had problems with this as well, but fixed them through limiting text output https://github.com/stripedpajamas/scat/issues/3

**Comment by cblgh** [comment]
closed!!!

commits: 
* https://github.com/cabal-club/cabal/commit/9bc3418ef5fc2041750e1d37083c43d4cbaff9e2
*  https://github.com/noffle/txt-blit/pull/3

1. emojis caused rendering problems
2. fullwidth characters (CJK, chinese japanese korean) caused rendering problems
to solve 1: use a grapheme-splitting library to correctly chunk messages into their constituents (individual characters, emojis + COMBINED emojis like purple hearts or people kissing)
use the split string to filter out characters in the upper astral planes of unicode (i.e. only keep characters in the basic plane, or with a code point below 65536)
to solve 2: patch txt-blit to account for fullwidth characters, see https://github.com/noffle/txt-blit/pull/3
