### ISSUE TITLE
Security & permissions discussion

### ISSUE THREAD

**Issue by cinnamon-bun** [cabal-club/cabal#43]
Does everyone in a cabal have the ability to edit and delete each others' messages?

What are the pros and cons of multiwriter hyperdb in this situation compared with a collection of hypercores or hyperdrives like Fritter?

**Comment by noffle** [comment]
Yeah, there are some problems with the hyperdb approach. I started on an implementation that uses a set of hypercores; the `kappa` branch.

**Comment by cblgh** [comment]
i don't think we have this issue anymore
