### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by noffle** [cabal-club/cabal#44]
I don't *seem* (?) to be peering with folks anymore. Creating this issue to track investigation.

**Comment by nikolaiwarner** [comment]
Today upon opening Cabal cli I'm seeing no users, no history, just me at dat://59813e3169b4b2a6d3741b077f80cce014d84d67b4a8f9fa4c19605b5cff637f

**Comment by cblgh** [comment]
i don't think we have this issue anymore, closing for now
