### ISSUE TITLE
Rendering issues with emojis

### ISSUE THREAD

**Issue by ralphtheninja** [cabal-club/cabal#55]
People have been mentioning this in the channels. Just thought I'd create an issue where we can gather some more information. I've created an `emoji-test` channel.

I noticed that some emojis doesn't cause any rendering issues, and some times it's random. Some other emojis are really consistent.

The telephone for example makes a really predictive pattern:

![screenshot from 2018-08-09 01-39-22](https://user-images.githubusercontent.com/308049/43869958-74f68578-9b75-11e8-80c8-2de1c899da62.png)

**Comment by noffle** [comment]
Nevermind, I can't repro with mutt.

**Comment by ralphtheninja** [comment]
![screenshot from 2018-08-09 03-43-49](https://user-images.githubusercontent.com/308049/43873328-8be63560-9b86-11e8-9ed9-c9106ae3d904.png)

```sh
node util.js
2
2
3
3
```

**Comment by ralphtheninja** [comment]
`boxen` also gets this wrong:

![screenshot from 2018-08-09 03-51-12](https://user-images.githubusercontent.com/308049/43873623-839fafb6-9b87-11e8-97d7-5aae830bffdd.png)

**Comment by ralphtheninja** [comment]
@noffle Maybe in `strlenAnsi()` we could do something like

1. Input `str`
2. Filter out all ansi stuff from `str`
3. Use https://github.com/orling/grapheme-splitter (or similar) to count the perceived characters

**Comment by noffle** [comment]
+1

**Comment by cblgh** [comment]
closed thanks to
* https://github.com/cabal-club/cabal/commit/9bc3418ef5fc2041750e1d37083c43d4cbaff9e2
*  https://github.com/noffle/txt-blit/pull/3
