### ISSUE TITLE
Introduce MOTD chat type

### ISSUE THREAD

**Issue by cblgh** [cabal-club/cabal#69]
used to set a message of the day for a particular channel such as
`cabal is a ----NO BURNOUT ZONE----` (shoutouts to @noffle <3)

spec
```
{
  type: 'chat/motd',
  content: {
    text: 'message of the day for the specified channel',
    channel: 'some channel name. if it didnt exist before, it does now!'
  }
}
```

**Comment by noffle** [comment]
When do you think we'd show the MOTD? On first join? Locked to the top of the chat area? Only when it gets changed?

**Comment by cblgh** [comment]
yeah i was thinking about that briefly, and i like how it's done in irssi ![](https://i.cblgh.org/2018-09/2576AWw.png)

slack has something similar ![](https://i.cblgh.org/2018-09/2577SyY.png)

**Comment by nikolaiwarner** [comment]
@noffle @cblgh 

I've implemented the motd feature on the cli and it uses the latest 'chat/motd' type message to set that for a channel. 

However, after MAX_MESSAGES have been sent after sending the 'chat/motd' message, it cant find a 'chat/motd' to use for the motd. How can I search back further (perhaps through all of history) for a specific type of message?

**Comment by cblgh** [comment]
🔥 🔥 🔥

**Comment by cblgh** [comment]
i'm not really sure of the `MAX_MESSAGES` part wrt the new database & multifeed, that'd be interesting to know how to query..

**Comment by noffle** [comment]
You can write a new kappa view for this. It scans _all_ messages with
type chat/motd and uses the one with the largest timestamp(?) as the
motd. Then you could expose this via an api on that kappa view to get
it, like

```js
this.db.api.motd.get(function (err, motdMessage) {
})
```

`lib/channels.js` is a good reference to start from.
