### ISSUE TITLE
alt-[1,9] shortcut doesn't work on macos

### ISSUE THREAD

**Issue by beingalink** [cabal-club/cabal#77]
As the title says. alt+number prints the alternate glyph for the respective number key as everywhere else on macos.

**Comment by noffle** [comment]
This might be a macos terminal setting?

**Comment by noffle** [comment]
maybe https://blog.remibergsma.com/2012/01/30/alt-key-aan-de-praat-in-osx-terminal/ ?

**Comment by beingalink** [comment]
I'm using iTerm2 but I found some settings for that there, too. The behavior in iTerm2 and Terminal app isn't perfect yet as on first usage some empty lines get inserted at the bottom but the channel switch gets executed just fine. Also in the default channel the separator line to the users panel gets a bit distorted.

**Comment by noffle** [comment]
@beingalink could you open an issue for these artifacts you're seeing? if possible with repro steps and screenshots!
