### ISSUE TITLE
feature suggestion: let cabal manage connections to several cabal keys with respective channels

### ISSUE THREAD

**Issue by beingalink** [cabal-club/cabal#79]
Same as with current irc clients where you can connect to several networks at once.

**Comment by noffle** [comment]
yassss! some of us were just talking about this.

[cabal-client](https://github.com/cabal-club/cabal-client) might be a good place for this, or maybe even a lower level `cabal-party` module, that managed several `cabal-core`s!

**Comment by cblgh** [comment]
i still want to try the tree view structure, but currently implemented in #85 / #89!
