### ISSUE TITLE
New db format proposal

### ISSUE THREAD

**Issue by karissa** [cabal-club/cabal#8]
The current way that we are getting the channel list will make things slow if there are tons of messages. Also, to get the message list you currently have to filter out the /metadata entry.

If instead, we do `/metadata/{channel}` and `/messages/{channel}/1` we can avoid these issues. Getting the channel list is then iterating on `/metadata`  (which there should only be one per channel).

**Comment by cblgh** [comment]
implemented in https://github.com/cabal-club/cabal-node/pull/2
