### ISSUE TITLE
CLI tool shows some messages like this.

### ISSUE THREAD

**Issue by 0101solar** [cabal-club/cabal#9]
![untitled](https://user-images.githubusercontent.com/38737206/40320344-5d9e09ec-5cf9-11e8-99e5-267ff59522d2.png)

**Comment by cblgh** [comment]
yeah that's by design, in case a client writes their own message format. (in this case someone tried to connect with the old [chatmesh](https://github.com/substack/chatmesh) client)

we could either ignore the message or print it out, currently we're logging it

**Comment by cblgh** [comment]
also cabal ps looks really sweet in your terminal haha

**Comment by 0101solar** [comment]
oh, ok. i thought it was something more drastic or bad
