### ISSUE TITLE
Urls in messages should be clickable

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal#95]
https://github.com/sindresorhus/terminal-link

**Comment by cblgh** [comment]
a random idea appears: we can do this at the same time as when we implement a terminal markdown parser

**Comment by noffle** [comment]
-1, since my terminal (termite) already handles this. In fact, every terminal emulator I've used on linux does this.

**Comment by cblgh** [comment]
i implemented this as terminal friendly markdown parsing in the latest pr, are you still -1 noffle?

**Comment by noffle** [comment]
Oh! I just didn't want URLs to be auto-clickable in case it fought with my terminal emulator :)   Being able to make arbitrary text clickable sounds useful though.
